extends Node

@warning_ignore("unused_signal")
signal load_scene(path: String)
@warning_ignore("unused_signal")
signal game_started()
@warning_ignore("unused_signal")
signal enemy_died()
@warning_ignore("unused_signal")
signal game_over()
@warning_ignore("unused_signal")
signal player_put_on_spectral_mask()
@warning_ignore("unused_signal")
signal player_took_off_spectral_mask()
@warning_ignore("unused_signal")
signal enemy_recycled()
@warning_ignore("unused_signal")
signal score_changed(current_score: float)
